//
// Generated file, do not edit! Created by opp_msgc 4.5 from src/discovery.msg.
//

#ifndef _DISCOVERY_M_H_
#define _DISCOVERY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "query.h"
// }}



/**
 * Class generated from <tt>src/discovery.msg</tt> by opp_msgc.
 * <pre>
 * packet Dmsg { 
 *    
 *     unsigned int source;
 *     unsigned int destination;
 *     unsigned int mtype;
 *     mainQuery mq;
 *   
 * }
 * </pre>
 */
class Dmsg : public ::cPacket
{
  protected:
    unsigned int source_var;
    unsigned int destination_var;
    unsigned int mtype_var;
    mainQuery mq_var;

  private:
    void copy(const Dmsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Dmsg&);

  public:
    Dmsg(const char *name=NULL, int kind=0);
    Dmsg(const Dmsg& other);
    virtual ~Dmsg();
    Dmsg& operator=(const Dmsg& other);
    virtual Dmsg *dup() const {return new Dmsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getSource() const;
    virtual void setSource(unsigned int source);
    virtual unsigned int getDestination() const;
    virtual void setDestination(unsigned int destination);
    virtual unsigned int getMtype() const;
    virtual void setMtype(unsigned int mtype);
    virtual mainQuery& getMq();
    virtual const mainQuery& getMq() const {return const_cast<Dmsg*>(this)->getMq();}
    virtual void setMq(const mainQuery& mq);
};

inline void doPacking(cCommBuffer *b, Dmsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Dmsg& obj) {obj.parsimUnpack(b);}


#endif // _DISCOVERY_M_H_
