//
// Generated file, do not edit! Created by opp_msgc 4.5 from src/subquery.msg.
//

#ifndef _SUBQUERY_M_H_
#define _SUBQUERY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "query.h"
// }}



/**
 * Class generated from <tt>src/subquery.msg</tt> by opp_msgc.
 * <pre>
 * packet SQM { 
 *   
 *     unsigned int source;
 *     unsigned int destination;
 *     unsigned int mtype;
 *     unsigned int extra;
 *     subQuery sq;
 *   
 * }
 * </pre>
 */
class SQM : public ::cPacket
{
  protected:
    unsigned int source_var;
    unsigned int destination_var;
    unsigned int mtype_var;
    unsigned int extra_var;
    subQuery sq_var;

  private:
    void copy(const SQM& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SQM&);

  public:
    SQM(const char *name=NULL, int kind=0);
    SQM(const SQM& other);
    virtual ~SQM();
    SQM& operator=(const SQM& other);
    virtual SQM *dup() const {return new SQM(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getSource() const;
    virtual void setSource(unsigned int source);
    virtual unsigned int getDestination() const;
    virtual void setDestination(unsigned int destination);
    virtual unsigned int getMtype() const;
    virtual void setMtype(unsigned int mtype);
    virtual unsigned int getExtra() const;
    virtual void setExtra(unsigned int extra);
    virtual subQuery& getSq();
    virtual const subQuery& getSq() const {return const_cast<SQM*>(this)->getSq();}
    virtual void setSq(const subQuery& sq);
};

inline void doPacking(cCommBuffer *b, SQM& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SQM& obj) {obj.parsimUnpack(b);}


#endif // _SUBQUERY_M_H_
