
cplusplus {{ 
    #include "query.h"
    #include <vector>
    #include <string>
 //   typedef opp_string strt;
    
    
    }} // C++ typedef
struct strtype;
//class noncobject strt;


 
message rdMessage
{
   unsigned int ID=0; 
   bool flag=true;
    int source=0;
    int destination=0;
    int hopCount = 0;
    int mtype=0;
    int intContent=0;
    int intContentSD=0;
    int intValue=0;
  // strtype  mainContent;
  	strtype mainContent=DEFULT_STC;
  	strtype stringContent=DEFULT_STC;
 //	int originSource;
  
}
